/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.rpg;

import static java.awt.SystemColor.window;
import java.awt.event.*;
import java.awt.*;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;


/**
 *
 * @author Carlos
 */
public class rpg extends javax.swing.JFrame {

    /**
     * Creates new form rpg
     */
    
    public rpg() {
        initComponents();
        
    }
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pKnight = new javax.swing.JLabel();
        pValkyrie = new javax.swing.JLabel();
        bossDragon = new javax.swing.JLabel();
        pHealer = new javax.swing.JLabel();
        atack = new javax.swing.JButton();
        barraDragon = new javax.swing.JProgressBar();
        vidaDragon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        impale = new javax.swing.JButton();
        charge = new javax.swing.JButton();
        vidaKnight = new javax.swing.JLabel();
        vidaValkyrie = new javax.swing.JLabel();
        vidaHealer = new javax.swing.JLabel();
        barraValkyrie = new javax.swing.JProgressBar();
        barraKnight = new javax.swing.JProgressBar();
        barraHealer = new javax.swing.JProgressBar();
        heal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mainMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitOption = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1100, 652));
        getContentPane().setLayout(null);

        pKnight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/knight100x100mirror.png"))); // NOI18N
        getContentPane().add(pKnight);
        pKnight.setBounds(340, 430, 100, 100);

        pValkyrie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/valkyrie100x100mirror.png"))); // NOI18N
        getContentPane().add(pValkyrie);
        pValkyrie.setBounds(60, 330, 100, 100);

        bossDragon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bossDragon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/PieceDragonbltG.png"))); // NOI18N
        getContentPane().add(bossDragon);
        bossDragon.setBounds(670, 190, 400, 400);

        pHealer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/djinn100x100mirror.png"))); // NOI18N
        pHealer.setToolTipText("");
        getContentPane().add(pHealer);
        pHealer.setBounds(130, 460, 100, 100);

        atack.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        atack.setText("Atack!");
        atack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atackMouseClicked(evt);
            }
        });
        getContentPane().add(atack);
        atack.setBounds(20, 10, 87, 31);

        barraDragon.setMaximum(500);
        barraDragon.setValue(500);
        barraDragon.setForeground(Color.red);
        barraDragon.setBackground(Color.orange);
        barraDragon.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        getContentPane().add(barraDragon);
        barraDragon.setBounds(660, 120, 390, 23);

        vidaDragon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vidaDragon.setForeground(new java.awt.Color(255, 255, 255));
        vidaDragon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaDragon.setText("500");
        getContentPane().add(vidaDragon);
        vidaDragon.setBounds(820, 150, 70, 17);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 0, 0);

        impale.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        impale.setText("Impale");
        impale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                impaleMouseClicked(evt);
            }
        });
        impale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impaleActionPerformed(evt);
            }
        });
        getContentPane().add(impale);
        impale.setBounds(20, 50, 90, 30);

        charge.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        charge.setText("Charge");
        charge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chargeMouseClicked(evt);
            }
        });
        getContentPane().add(charge);
        charge.setBounds(20, 90, 90, 30);

        vidaKnight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vidaKnight.setForeground(new java.awt.Color(255, 255, 255));
        vidaKnight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaKnight.setText("200");
        getContentPane().add(vidaKnight);
        vidaKnight.setBounds(370, 540, 27, 17);

        vidaValkyrie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vidaValkyrie.setForeground(new java.awt.Color(255, 255, 255));
        vidaValkyrie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaValkyrie.setText("150");
        getContentPane().add(vidaValkyrie);
        vidaValkyrie.setBounds(87, 440, 50, 17);

        vidaHealer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vidaHealer.setForeground(new java.awt.Color(255, 255, 255));
        vidaHealer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vidaHealer.setText("100");
        getContentPane().add(vidaHealer);
        vidaHealer.setBounds(160, 560, 50, 14);

        barraValkyrie.setMaximum(150);
        barraValkyrie.setValue(150);
        getContentPane().add(barraValkyrie);
        barraValkyrie.setBounds(70, 430, 80, 10);

        barraKnight.setMaximum(200);
        barraKnight.setValue(200);
        getContentPane().add(barraKnight);
        barraKnight.setBounds(340, 530, 90, 10);

        barraHealer.setValue(100);
        getContentPane().add(barraHealer);
        barraHealer.setBounds(140, 550, 90, 10);

        heal.setFont(new java.awt.Font("Viner Hand ITC", 1, 12)); // NOI18N
        heal.setText("HEAL!!");
        heal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healMouseClicked(evt);
            }
        });
        getContentPane().add(heal);
        heal.setBounds(120, 50, 90, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/MP_DragonsLair5_8_bd.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -20, 1100, 650);

        fileMenu.setText("File");

        mainMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mainMenu.setText("Main Menu");
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });
        fileMenu.add(mainMenu);
        fileMenu.add(jSeparator1);

        exitOption.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        exitOption.setText("Rage Quit");
        exitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitOptionActionPerformed(evt);
            }
        });
        fileMenu.add(exitOption);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1116, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atackMouseClicked
        Victoria v = new Victoria();
        v.setVisible(false);
        Derrota f = new Derrota();
        f.setVisible(false);
        
        bossDragon.setVisible(true);
        pKnight.setVisible(true);
        pValkyrie.setVisible(true);
        pHealer.setVisible(true);
        
        int int_vidaDragon = Integer.parseInt(vidaDragon.getText());      
        int int_vidaKnight = Integer.parseInt(vidaKnight.getText());
        int int_vidaValkyrie = Integer.parseInt(vidaValkyrie.getText());
        int int_vidaHealer = Integer.parseInt(vidaHealer.getText());
        
        boolean isClicked = (int_vidaKnight <= 0);
        
        if(!isClicked){
            int_vidaDragon-= 5 + (Math.random()*1000)%5;
            if(int_vidaDragon > 0){
                vidaDragon.setText(""+int_vidaDragon);
                barraDragon.setValue(int_vidaDragon);
            }
            else if(int_vidaDragon <= 0){
                vidaDragon.setText(""+0);
                barraDragon.setValue(0);
            }
            if(int_vidaDragon > 0){
                int_vidaKnight-= 5 + (Math.random()*100)%5;
                int_vidaValkyrie-= 5 + (Math.random()*100)%5;
                int_vidaHealer-= 5 + (Math.random()*100)%5;

                

                if(int_vidaKnight > 0){                
                    vidaKnight.setText(""+int_vidaKnight);
                    barraKnight.setValue(int_vidaKnight);
                }
                else if(int_vidaKnight <= 0){
                    vidaKnight.setText(""+0);
                    barraKnight.setValue(0);
                    isClicked = true;
                }
                if(int_vidaValkyrie > 0){                
                    vidaValkyrie.setText(""+int_vidaValkyrie);
                    barraValkyrie.setValue(int_vidaValkyrie);
                }
                else if(int_vidaValkyrie <= 0){
                    vidaValkyrie.setText(""+0);
                    barraValkyrie.setValue(0);
                }
                if(int_vidaHealer > 0){                
                    vidaHealer.setText(""+int_vidaHealer);
                    barraHealer.setValue(int_vidaHealer);
                }  
                else if(int_vidaHealer <= 0){      
                    vidaHealer.setText(""+0);
                    barraHealer.setValue(0);
                }
            }
        }
        
        if(int_vidaDragon <= 0){
            bossDragon.setVisible(false);
            v.setVisible(true);
        }
        if(int_vidaKnight <= 0 ){
            pKnight.setVisible(false);
        }
        if(int_vidaValkyrie <= 0){
            pValkyrie.setVisible(false);                   
        }
        if(int_vidaHealer <= 0){
            pHealer.setVisible(false);
        }
        if(int_vidaKnight <= 0 && int_vidaValkyrie <= 0 && int_vidaHealer <= 0){
            f.setVisible(true);
        }
    }//GEN-LAST:event_atackMouseClicked

    private void impaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_impaleActionPerformed

    private void impaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_impaleMouseClicked
        // TODO add your handling code here:
        Victoria v = new Victoria();
        v.setVisible(false);
        Derrota f = new Derrota();
        f.setVisible(false);
        
        bossDragon.setVisible(true);
        pKnight.setVisible(true);
        pValkyrie.setVisible(true);
        pHealer.setVisible(true);
        
        int int_vidaDragon = Integer.parseInt(vidaDragon.getText());        
        int int_vidaKnight = Integer.parseInt(vidaKnight.getText());
        int int_vidaValkyrie = Integer.parseInt(vidaValkyrie.getText());
        int int_vidaHealer = Integer.parseInt(vidaHealer.getText());
        
        boolean isClicked = (int_vidaValkyrie <= 0);
        
        if(!isClicked){
            int_vidaDragon-= 45;
            if(int_vidaDragon > 0){
                vidaDragon.setText(""+int_vidaDragon);
                barraDragon.setValue(int_vidaDragon);
            }
            else if(int_vidaDragon <= 0){
                vidaDragon.setText(""+0);
                barraDragon.setValue(0);
            }
            if(int_vidaDragon > 0){
                int_vidaKnight-= 5 + (Math.random()*100)%5;
                int_vidaValkyrie-= 5 + (Math.random()*100)%5;
                int_vidaHealer-= 5 + (Math.random()*100)%5;

                

                if(int_vidaKnight > 0){                
                    vidaKnight.setText(""+int_vidaKnight);
                    barraKnight.setValue(int_vidaKnight);
                }
                else if(int_vidaKnight <= 0){
                    vidaKnight.setText(""+0);
                    barraKnight.setValue(0);
                    isClicked = true;
                }
                if(int_vidaValkyrie > 0){                
                    vidaValkyrie.setText(""+int_vidaValkyrie);
                    barraValkyrie.setValue(int_vidaValkyrie);
                }
                else if(int_vidaValkyrie <= 0){
                    vidaValkyrie.setText(""+0);
                    barraValkyrie.setValue(0);
                }
                if(int_vidaHealer > 0){                
                    vidaHealer.setText(""+int_vidaHealer);
                    barraHealer.setValue(int_vidaHealer);
                }  
                else if(int_vidaHealer <= 0){      
                    vidaHealer.setText(""+0);
                    barraHealer.setValue(0);
                }
            }
        }
        if(int_vidaDragon <= 0){
            bossDragon.setVisible(false);
            v.setVisible(true);
        }
        if(int_vidaKnight <= 0 ){
            pKnight.setVisible(false);
        }
        if(int_vidaValkyrie <= 0){
            pValkyrie.setVisible(false);
        }
        if(int_vidaHealer <= 0){
            pHealer.setVisible(false);
        }
        if(int_vidaKnight <= 0 && int_vidaValkyrie <= 0 && int_vidaHealer <= 0){
            f.setVisible(true);
        }
    
    }//GEN-LAST:event_impaleMouseClicked

    private void chargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chargeMouseClicked
        // TODO add your handling code here:
        Victoria v = new Victoria();
        v.setVisible(false);
        Derrota f = new Derrota();
        f.setVisible(false);
        
        bossDragon.setVisible(true);
        pKnight.setVisible(true);
        pValkyrie.setVisible(true);
        pHealer.setVisible(true);
        int int_vidaDragon = Integer.parseInt(vidaDragon.getText());   
        int int_vidaKnight = Integer.parseInt(vidaKnight.getText());
        int int_vidaValkyrie = Integer.parseInt(vidaValkyrie.getText());
        int int_vidaHealer = Integer.parseInt(vidaHealer.getText());
        
        boolean isClicked = (int_vidaKnight <= 0);
        
        if(!isClicked){
            if(int_vidaDragon >= 50 && int_vidaDragon <=150){
                int_vidaDragon-= 100;
            }
            
            if(int_vidaDragon > 0){
                vidaDragon.setText(""+int_vidaDragon);
                barraDragon.setValue(int_vidaDragon);
            }
            
            else if(int_vidaDragon <= 0){
                vidaDragon.setText(""+0);
                barraDragon.setValue(0);
            }
            
            if(int_vidaDragon > 0){
                int_vidaKnight-= 80;
                int_vidaValkyrie-= 80;
                int_vidaHealer-= 80;               

                if(int_vidaKnight > 0){                
                    vidaKnight.setText(""+int_vidaKnight);
                    barraKnight.setValue(int_vidaKnight);
                }
                else if(int_vidaKnight <= 0){
                    vidaKnight.setText(""+0);
                    barraKnight.setValue(0);
                    isClicked = true;
                }
                if(int_vidaValkyrie > 0){                
                    vidaValkyrie.setText(""+int_vidaValkyrie);
                    barraValkyrie.setValue(int_vidaValkyrie);
                }
                else if(int_vidaValkyrie <= 0){
                    vidaValkyrie.setText(""+0);
                    barraValkyrie.setValue(0);
                }
                if(int_vidaHealer > 0){                
                    vidaHealer.setText(""+int_vidaHealer);
                    barraHealer.setValue(int_vidaHealer);
                }  
                else if(int_vidaHealer <= 0){      
                    vidaHealer.setText(""+0);
                    barraHealer.setValue(0);
                }
            }
        }
        
        if(int_vidaDragon <= 0){
            bossDragon.setVisible(false);
            v.setVisible(true);
        }
        if(int_vidaKnight <= 0 ){
            pKnight.setVisible(false);
        }
        if(int_vidaValkyrie <= 0){
            pValkyrie.setVisible(false);                   
        }
        if(int_vidaHealer <= 0){
            pHealer.setVisible(false);
        }
        if(int_vidaKnight <= 0 && int_vidaValkyrie <= 0 && int_vidaHealer <= 0){
            f.setVisible(true);
        }
    }//GEN-LAST:event_chargeMouseClicked

    private void healMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healMouseClicked
        // TODO add your handling code here:
        Victoria v = new Victoria();
        v.setVisible(false);
        Derrota f = new Derrota();
        f.setVisible(false);
        
        int int_vidaDragon = Integer.parseInt(vidaDragon.getText());
        int int_vidaKnight = Integer.parseInt(vidaKnight.getText());
        int int_vidaValkyrie = Integer.parseInt(vidaValkyrie.getText());
        int int_vidaHealer = Integer.parseInt(vidaHealer.getText());
        
        boolean ifClicked = (int_vidaHealer == 0);
        
        if(!ifClicked){
            if(int_vidaDragon > 0){
                if (int_vidaKnight < 200){
                    int_vidaKnight+= 50;
                    vidaKnight.setText(""+int_vidaKnight);
                    barraKnight.setValue(int_vidaKnight);
                    if(int_vidaKnight >= 200){
                        int_vidaKnight = 200;
                        vidaKnight.setText(""+int_vidaKnight);
                        barraKnight.setValue(int_vidaKnight);
                    }
                }
                if (int_vidaValkyrie < 150){
                    int_vidaValkyrie+= 50;
                    vidaValkyrie.setText(""+int_vidaValkyrie);
                    barraValkyrie.setValue(int_vidaValkyrie);
                    if (int_vidaValkyrie >= 150){
                        int_vidaValkyrie = 150;
                        vidaValkyrie.setText(""+int_vidaValkyrie);
                        barraValkyrie.setValue(int_vidaValkyrie);
                     }
                }                
                if (int_vidaHealer < 100){
                    int_vidaHealer+= 50;
                    vidaHealer.setText(""+int_vidaHealer);
                    barraHealer.setValue(int_vidaHealer);
                    if (int_vidaHealer >= 100){
                        int_vidaHealer = 100;
                        vidaHealer.setText(""+int_vidaHealer);
                        barraHealer.setValue(int_vidaHealer);
                    }
                }                
            }            
        }
        if(int_vidaKnight <= 0 && int_vidaValkyrie <= 0 && int_vidaHealer <= 0){
            f.setVisible(true);
        }
    }//GEN-LAST:event_healMouseClicked

    private void exitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitOptionActionPerformed
        close();
    }//GEN-LAST:event_exitOptionActionPerformed

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        // TODO add your handling code here:
        close();
        Main_Menu s = new Main_Menu();
        s.setVisible(true);
    }//GEN-LAST:event_mainMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atack;
    private javax.swing.JProgressBar barraDragon;
    private javax.swing.JProgressBar barraHealer;
    private javax.swing.JProgressBar barraKnight;
    private javax.swing.JProgressBar barraValkyrie;
    private javax.swing.JLabel bossDragon;
    private javax.swing.JButton charge;
    private javax.swing.JMenuItem exitOption;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton heal;
    private javax.swing.JButton impale;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mainMenu;
    private javax.swing.JLabel pHealer;
    private javax.swing.JLabel pKnight;
    private javax.swing.JLabel pValkyrie;
    private javax.swing.JLabel vidaDragon;
    private javax.swing.JLabel vidaHealer;
    private javax.swing.JLabel vidaKnight;
    private javax.swing.JLabel vidaValkyrie;
    // End of variables declaration//GEN-END:variables
}
